### PR TITLE
Issue #1 fix and adding more aliases

### LINKED ISSUE #1: Add example for each alias in README.md

### PR DESCRIPTION
**Pull request by justsaumit**
Fixes #1
Contributes in #2 

## Proposed Changes

  -Added shebang to bash_aliases file
  -Removed positional arguments from aliases
  -Replaced $HOME environment variable
  -Fixes error in #1
  -Ignore error messages for lsize function
  -addition of few conda aliases + comments for #2
  -replacing git-graph alias for #2 

## Screenshots
image

### CODE REVIEW

File: bash_aliases.sh [hunk 1]
```diff
@@ -1,26 +1,36 @@
...
+alias conda-remove-env='conda env remove --name'    # Removes a conda enviroment with the name as first argument($1)
+alias conda-eu="conda env update"                   # Updates the current conda environment
+alias conda-ls='conda env list'                     # List conda environments
+alias conda-lsp='conda list --name'                 # List conda packages                                          
+alias conda-i="conda install"                       # Installs a list of packages into a specified conda environment provided as arguments
+alias conda-r="conda remove"                        # Removes a list of packages from a specified conda environment provided as arguments
+
+#Git Aliases                                                
+
+alias git-graph="git log --graph --abbrev-commit --decorate --format=format:'%C(bold green)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold yellow)(%ar)%C(reset)%C(auto)%d%C(reset)%n''%C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all" # Simple and Beautiful way to display git log
```
Comment (Agrover112) [inline bash_aliases.sh]: I quite like the plain git-graph.  Can we create a separate alias or add an color option to the alias?

File: bash_aliases.sh [hunk 2]
```diff
@@ -1,26 +1,36 @@
...
+alias git-show-lastn=' bash $HOME/scripts/gitshowcom.sh' # Look behind at the nth commit back in the log.
 
 # Utils
-function lsize() { du -s ${1}/* | sort -rn | cut -f2- | xargs -d "\n" du -sh }
-alias ls-size='lsize $1wq'
+lsize() {
```
Comment (Agrover112) [inline bash_aliases.sh]: This seems too slow.

File: bash_aliases.sh [hunk 3]
```diff
@@ -1,26 +1,36 @@
...
-alias speedread='~/$USER/Downloads/speedread/speedread $1'
+alias speedread='$HOME/Downloads/speedread/speedread'
 
-function bat-help(){ $1 --help | batcat }  #Bat is requird
-alias bathelp='bat-help $1'
+#Bat is required
+bat_help() { 
+        "$1" --help | batcat 
+}
+alias bathelp='bat_help'
```
Comment (Agrover112) [inline bash_aliases.sh]: I'm following something-heuristic convention

File: bash_aliases.sh [hunk 4]
```diff
@@ -1,26 +1,36 @@
...
 # Conda Aliases                                                                  
-alias conda-remove-env='conda env remove --name $1'                             
-alias conda-create-env='conda create --name $1'                                 
-alias conda-lsp='conda list --name $1' # List conda packages                                          
-alias conda-ls='conda env list'        # List conda environments                                                  
-                                                                                 
-#Git Aliases                                                                     
-alias git-graph='git log --graph --oneline'                      # A simpler heuristic                                   
-alias git-show-lastn=' bash /home/meow/scripts/gitshowcom.sh $1' # Look behind at the nth commit back in the log.
+alias conda-create-env='conda env create --name'    # Creates a conda enviroment with the name as first argument($1)
```
Comment (Agrover112) [inline bash_aliases.sh:9]: was $1 redundant?

**Review by Agrover112 — CHANGES_REQUESTED** [review]
1. Can you pls revert the commad-heuristic back to the original name?
2. Also take a look at the git-graph comment.
3.  ls-size alias was removed put it back.

File: bash_aliases.sh (hunk 2 above)
Comment (Agrover112) [reply bash_aliases.sh]: It's getting stuck?

File: bash_aliases.sh (hunk 1 above)
Comment (justsaumit) [reply bash_aliases.sh]: Alright will make it with a different name and restore the original alias. What should I name this one?

File: bash_aliases.sh (hunk 3 above)
Comment (justsaumit) [reply bash_aliases.sh]: can u link to the convention? will read up on it! even in single line function you need to appy semicolon inside function
``` bash
function foo { bar ; }
```
which wasn't present in the original thus gave error. 
Do you wish to have the bat_help function be just like how I mentioned above?

File: bash_aliases.sh (hunk 4 above)
Comment (justsaumit) [reply bash_aliases.sh:9]: Yes, you can implement the $1 in your ```gitshowcom.sh``` script rather than using it in an alias :)

File: bash_aliases.sh (hunk 1 above)
Comment (Agrover112) [reply bash_aliases.sh]: Something along the lines of pretty? git-graph-pretty , pretty-git-graph...

File: bash_aliases.sh (hunk 3 above)
Comment (Agrover112) [reply bash_aliases.sh]: LOL I mean't I'm followng my own fn naming convention for aliases with bat-help; git-graph

File: bash_aliases.sh (hunk 2 above)
Comment (Agrover112) [reply bash_aliases.sh]: image 

Let's leave it like this lol

Comment (justsaumit) [reply bash_aliases.sh]: It is quite slow indeed and requires optimization. It could be that running the command on a different mountpoint which doesnt allow reading is producing error and since I have disabled errors to show up... it ultimately shows up as stuck :/
https://0x0.st/oJXc.mp4

like here's a demo
Wanted to ask why do you use the du command twice?

File: bash_aliases.sh (hunk 3 above)
Comment (justsaumit) [reply bash_aliases.sh]: Oh I'm pretty sure "-" denomination is not allowed for functions in POSIX shell that's why I renamed it from bat-help to bat_help. for alias it works yeah
I can change the alias bathelp to bat-help

File: bash_aliases.sh (hunk 2 above)
Comment (Agrover112) [reply bash_aliases.sh]: Because of this. After we get the list of these folders now we find the size within all of them. (I believe that's how it's working)
image

Comment (Agrover112) [reply bash_aliases.sh]: @justsaumit  actually I have no clue what's happending with the code lol. Let's not break what already worked lol. 

What terminal are you using? Is it Rust based?

File: bash_aliases.sh (hunk 4 above)
Comment (Agrover112) [reply bash_aliases.sh:9]: Is there any convention to not use arguments within aliases?

**Review by Agrover112 — APPROVED** [review]

File: bash_aliases.sh (hunk 2 above)
Comment (justsaumit) [reply bash_aliases.sh]: Like instead of writing this entire thing
```bash
du -s ./* | sort -rn | cut -f2- | xargs -d "\n" du -sh
```
you can use
```bash
  find . -mindepth 1 -maxdepth 1 | xargs -d "\n" du -sh | sort -hr
```
image

#### Explanation: 
In 1st line I basically use a for loop to make 10 files each with around size of 'n' MB corresponding to their name. So 1.txt is about 1MB , 2.txt is about 2MB so on

2nd line is your original lsize function.

In 3rd line I try to minimize the usage of du and instead use find command.

_Funfact!_ you can just use 
```bash 
ls -Ssh1
``` 
and get almost the same result
image
Almost same because ```ls``` doesn't do well calculating the size of directories, hence you have to use du at some point.

### Benchmarking
Using time command to find which operation is more efficient and redirecting output to /dev/null so we just see the time command output.
image

Comment (justsaumit) [reply bash_aliases.sh]: it's zsh 5.9 with [powerlevel10k](https://github.com/romkatv/powerlevel10k) as zsh theme/prompt. Pretty cool comes with git indication and all. Starship prompt is rust based i think

Comment (Agrover112) [reply bash_aliases.sh]: If this works for directories let's merge it

Comment (justsaumit) [reply bash_aliases.sh]: It does, however you do try 
```bash
find . -mindepth 1 -maxdepth 1 | xargs -d "\n" du -sh | sort -hr
``` 
on your own system and if it works and produces the same result. 
Then make sure to merge the pr :)

Comment (Agrover112) [reply bash_aliases.sh]: Hmm, I like your method more since it shows the files as well as the sub-folders.
